### ISSUE TITLE
Make it easier to get custom metrics

### ISSUE THREAD

**Issue by mholden8** [PerkTutor/PerkEvaluator#57]
At present, only five metrics are available to the user by default. If a user wants more metrics they need to go to the PerkEvaluator repository on Github, download the metrics, unzip the metrics, and import them into Slicer.

If would be nice if there were a button in the PerkEvaluator module that automatically downloaded and imported these metrics into Slicer.

**Comment by matthewsholden** [comment]
The previous fix imported all of the additional Python Metrics found in the repository. This significantly clutters the scene, especially because of the pervasive metrics.

Instead it would be nice if the user could select exactly which metrics they wished to import.

Here's some example code on how the Slicer dialogs can be used to do this:

```python
ioManager = slicer.app.ioManager()
properties = [ "fileNames": [ "C:/path/to/metric1.py", "C:/path/to/metric2.py" ] ]
ioManager.openDialog( "NoFile", slicer.qSlicerFileDialog.Read, properties )
```
